### ISSUE TITLE
Add a small CONTRIBUTING.md

### ISSUE THREAD

**Issue by schulze** [Qabel/qabel#13]
The file should explain, that issues should be opened in a sub-repository, if it fits better there.

I believe this will mostly be important for issues related to
* documentation -> www.github.com/Qabel/qabel.github.io.
* core functionality ->  www.github.com/Qabel/qabel-core.
* drop server ->  www.github.com/Qabel/qabel.drop.
* storage server ->  www.github.com/Qabel/qabel-storage.

**Comment by thechauffeur** [comment]
* [ ] What you said
* [ ] As a fallback people should report issues in `qabel-desktop` or `qabel-android` depending on which client they used for testing. As a fallback for that people should use this repository.
* [ ] The other repositories need a (small) `CONTRIBUTUNG.md` file, too.

Maybe we should move the `CONTRIBUTUNG.md` file to this repository (and patch) it a bit and then just reference this file in the other repositories. Maybe repositories like `qabel-drop` and `qabel-storage` are an exception to this (e.g. because they are written in other programming languages).

**Comment by thechauffeur** [comment]
@Qabel/developer what do you think?

**Comment by cburkert** [comment]
I agree with @thechauffeur. I'd suggest that we write a contributing section in the readme files linking to a contributing file in this meta repo.

**Comment by jasinai** [comment]
Sounds good.

**Comment by thechauffeur** [comment]
This repository is deprecated and a contribution guideline is no longer needed.
