### ISSUE TITLE
Use PID files instead of lsof and netstat

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel#14]
Is there any reason why we do not use PID files to store the process identifiers of the spawned drop server and storage server processes and instead grep them from lsof and netstat?
The latter isn't very elegant.

**Comment by hartmannaf** [comment]
It doesnt seem to be much easier to get the pid from Java prozess class, or is there a easy way to accomplish this?

**Comment by thechauffeur** [comment]
You have the following options.
1. Directly patch `qabel-drop` and `qabel-storage` so that these programs provide an command line option to create a PID file.
2. Patch build.gradle so that all 4 tasks like `startDropServerUnix` create a PID file -- e.g. https://github.com/Qabel/qabel/blob/master/build.gradle#L112. For `qabel-drop` you could just use [gunicorn -p file](http://docs.gunicorn.org/en/latest/settings.html?highlight=pid#pidfile) to start the drop server to get a PID file. I'm not familiar with node.js so I don't know how to this for the storage server.
3. Remember the PIDs in gradle and reference them in the kill task.

In case 1 and 2 the [`killAllTestProcesses`](https://github.com/Qabel/qabel/blob/master/build.gradle#L37) task would use PID files and kill only the processes referenced in each file.

@cburkert told me you work on another solution using gradle tasks as instances and kill them. I think this is a good idea.
