### ISSUE TITLE
Internationalization and localization

### ISSUE THREAD

**Issue by schulze** [Qabel/qabel#17]
(Or  i18n and l10n if you need to.)

We should start to think about this early. I guess there will be some standard gettext-like way to handle this in Java (on Android). We also need to decide which languages we want to translate to and how we can come up with translations.

**Comment by thechauffeur** [comment]
You are right. We have to talk about this (e.g. do we need / want to touch the core or is it UI repositories only).

If we have to decide which language will be supported first / best / whatever we should decide for English. What I mean is that it is bad to show some untranslated error output / stack trace etc. to the user but if this happens it would be better to have this in English.

German will be the only other language supported at BETA release (because we obviously expect to have many German testers).

**Comment by thechauffeur** [comment]
This issue is deprecated.
